/**
 * The Phase 3 career catalog.
 *
 * This is authored content, not code: `prisma/seed.ts` upserts it by slug, so
 * running the seed repeatedly always produces the same catalog. Adding a
 * career here and re-seeding is all it takes — no frontend change.
 *
 * `icon` is a Lucide icon name resolved through src/lib/careers/icons.ts. That
 * registry imports each icon explicitly, so a typo here fails the build rather
 * than rendering a blank square.
 */

export type SeedCategory =
  | "SOFTWARE_DEVELOPMENT"
  | "DATA_AND_AI"
  | "INFRASTRUCTURE_AND_CLOUD"
  | "SECURITY"
  | "DESIGN_AND_PRODUCT"
  | "OTHER_TECHNOLOGY";

export type SeedDifficulty = "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
export type SeedDemand = "MODERATE" | "HIGH" | "VERY_HIGH";

export interface SeedCareer {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  mainFocus: string;
  icon: string;
  category: SeedCategory;
  difficulty: SeedDifficulty;
  estimatedLearningTime: string;
  demandLevel: SeedDemand;
  builds: string[];
  learningAreas: string[];
  suitedFor: string[];
  challenges: string[];
  technologies: string[];
  related: string[];
}

export const CAREERS: SeedCareer[] = [
  {
    slug: "frontend-developer",
    name: "Frontend Developer",
    shortDescription: "Build the interfaces people interact with every day.",
    description:
      "A frontend developer builds the part of a product you can actually see and touch — the buttons, forms, layouts and animations. You take a design and turn it into something that works in a real browser, on a phone as well as a laptop, and stays fast and usable when real people start clicking around. Most days are a mix of writing interface code, wiring it to data from a backend, and fixing the gap between how something looked in a design and how it behaves once it's real.",
    mainFocus: "User interface and interaction",
    icon: "Blocks",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "BEGINNER",
    estimatedLearningTime: "5–8 months",
    demandLevel: "VERY_HIGH",
    builds: [
      "Web applications people use daily",
      "Admin dashboards and internal tools",
      "E-commerce storefronts and checkout flows",
      "Marketing sites and interactive landing pages",
      "Design systems and shared component libraries",
    ],
    learningAreas: [
      "Programming fundamentals",
      "HTML and semantic structure",
      "CSS and responsive layout",
      "JavaScript",
      "Git and GitHub",
      "A component framework such as React",
      "TypeScript",
      "Working with APIs",
      "Accessibility",
      "Testing and deployment",
    ],
    suitedFor: [
      "You like seeing results immediately on screen",
      "You care how things look and feel to use",
      "You enjoy solving puzzles with layout and interaction",
      "You are patient with detail",
      "You like working close to designers and users",
    ],
    challenges: [
      "The same code can behave differently across browsers and devices",
      "Application state gets complicated faster than you expect",
      "Accessibility is easy to ignore and hard to retrofit",
      "Performance problems are often invisible until they aren't",
      "The tooling ecosystem changes quickly",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "Vite",
    ],
    related: [
      "full-stack-developer",
      "ui-ux-designer",
      "mobile-app-developer",
      "backend-developer",
    ],
  },
  {
    slug: "backend-developer",
    name: "Backend Developer",
    shortDescription: "Build the logic, data and APIs behind every product.",
    description:
      "A backend developer builds the part of a product nobody sees but everybody depends on. When you log in, search for something, or place an order, backend code decides what is allowed, where the data lives, and what happens next. The work is about modelling a problem correctly, storing data so it stays consistent, and exposing it through APIs that other developers — including frontend developers — can use without surprises.",
    mainFocus: "Server logic, data and APIs",
    icon: "Server",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "INTERMEDIATE",
    estimatedLearningTime: "6–9 months",
    demandLevel: "VERY_HIGH",
    builds: [
      "REST and GraphQL APIs",
      "Authentication and permission systems",
      "Database schemas and queries",
      "Payment and billing logic",
      "Background jobs and scheduled tasks",
    ],
    learningAreas: [
      "Programming fundamentals",
      "A backend language such as Python, Java or Node.js",
      "Git and GitHub",
      "Databases and SQL",
      "API design",
      "Authentication and security basics",
      "Caching and background jobs",
      "Testing",
      "Deployment and monitoring",
    ],
    suitedFor: [
      "You like thinking about how a system fits together",
      "You enjoy logic and data more than visual design",
      "You are careful about correctness and edge cases",
      "You like problems with a definite right answer",
      "You want to understand what happens under the hood",
    ],
    challenges: [
      "Mistakes can corrupt real data, so care matters more than speed",
      "Debugging spans services, queues and databases at once",
      "Security failures are quiet until they are expensive",
      "Designing a schema you won't regret takes experience",
      "Progress is less visible than on the frontend",
    ],
    technologies: [
      "Node.js",
      "Python",
      "Java",
      "Go",
      "PostgreSQL",
      "Redis",
      "Docker",
      "REST APIs",
    ],
    related: [
      "full-stack-developer",
      "data-engineer",
      "devops-engineer",
      "database-engineer",
    ],
  },
  {
    slug: "full-stack-developer",
    name: "Full Stack Developer",
    shortDescription: "Carry a feature from database schema to final pixel.",
    description:
      "A full stack developer works on both sides of a product. You might design a database table in the morning, write the API that reads from it, then build the screen that displays it. This is common at startups and small teams, where owning a whole feature is faster than passing it between specialists. The trade-off is breadth: you cover more ground, so you go less deep than someone focused on one side.",
    mainFocus: "End-to-end feature ownership",
    icon: "Layers",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "INTERMEDIATE",
    estimatedLearningTime: "9–14 months",
    demandLevel: "VERY_HIGH",
    builds: [
      "Complete web products, front to back",
      "Internal tools used by a whole company",
      "SaaS applications with accounts and billing",
      "Prototypes that become real products",
      "Integrations between systems",
    ],
    learningAreas: [
      "Programming fundamentals",
      "HTML, CSS and JavaScript",
      "A frontend framework",
      "A backend language and framework",
      "Git and GitHub",
      "Databases and SQL",
      "API design",
      "Authentication",
      "Testing",
      "Deployment",
    ],
    suitedFor: [
      "You are curious about how the whole system works",
      "You like owning something end to end",
      "You enjoy variety more than deep specialisation",
      "You are comfortable being a beginner in something often",
      "You want to build your own products one day",
    ],
    challenges: [
      "There is simply more to learn before you feel competent",
      "It is easy to be shallow in both halves rather than solid in one",
      "Context switching between frontend and backend is tiring",
      "You are often the person who has to debug across the whole stack",
      "Choosing what not to learn becomes a real skill",
    ],
    technologies: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "Docker",
      "REST APIs",
    ],
    related: [
      "frontend-developer",
      "backend-developer",
      "software-engineer",
      "devops-engineer",
    ],
  },
  {
    slug: "software-engineer",
    name: "Software Engineer",
    shortDescription: "Design and build software systems that have to last.",
    description:
      "Software engineer is the broadest title in the industry. It usually means someone who builds software as a discipline rather than for one specific surface — thinking about design, correctness, testing, maintenance and the people who will read the code next. Many engineers work on products that aren't websites at all: desktop applications, developer tools, internal platforms, or the systems other teams build on.",
    mainFocus: "General software design and construction",
    icon: "Code2",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "INTERMEDIATE",
    estimatedLearningTime: "9–14 months",
    demandLevel: "VERY_HIGH",
    builds: [
      "Applications and services across many platforms",
      "Developer tools and internal libraries",
      "Platform code other teams depend on",
      "Data processing and automation systems",
      "Long-lived systems that need to be maintained for years",
    ],
    learningAreas: [
      "Programming fundamentals",
      "Data structures and algorithms",
      "Git and GitHub",
      "A primary language, learned deeply",
      "Testing and debugging",
      "Software design and architecture",
      "Databases",
      "Version control workflows and code review",
      "Deployment",
    ],
    suitedFor: [
      "You like problem solving in the abstract",
      "You want fundamentals that transfer between jobs",
      "You care about writing code other people can read",
      "You are willing to learn concepts before frameworks",
      "You are not sure which speciality you want yet",
    ],
    challenges: [
      "The title is vague, so job descriptions vary enormously",
      "Fundamentals take longer to learn than a framework",
      "Interviews often test algorithms you rarely use day to day",
      "Legacy code is a large part of the real job",
      "You will spend more time reading code than writing it",
    ],
    technologies: [
      "Python",
      "Java",
      "TypeScript",
      "Go",
      "Git",
      "PostgreSQL",
      "Docker",
      "Linux",
    ],
    related: [
      "full-stack-developer",
      "backend-developer",
      "solutions-architect",
      "qa-test-engineer",
    ],
  },
  {
    slug: "ai-engineer",
    name: "AI Engineer",
    shortDescription: "Build products on top of language models and AI APIs.",
    description:
      "An AI engineer builds real applications using models that already exist, rather than training new ones from scratch. The work looks a lot like software engineering with an unusual component in the middle: the model is powerful but unpredictable, so much of the job is designing around that — giving it the right context, checking what comes back, and measuring whether the whole thing actually works. It is one of the newest roles in tech and the expectations are still settling.",
    mainFocus: "Applications powered by AI models",
    icon: "Bot",
    category: "DATA_AND_AI",
    difficulty: "ADVANCED",
    estimatedLearningTime: "8–12 months",
    demandLevel: "VERY_HIGH",
    builds: [
      "AI assistants and chat interfaces",
      "Retrieval systems over a company's own documents",
      "Agents that carry out multi-step tasks",
      "Model-powered features inside existing products",
      "Evaluation pipelines that measure output quality",
    ],
    learningAreas: [
      "Programming fundamentals",
      "Python",
      "Git and GitHub",
      "APIs and backend basics",
      "How language models actually behave",
      "Prompting and context design",
      "Retrieval and vector search",
      "Evaluation and testing of non-deterministic output",
      "Cost, latency and safety considerations",
    ],
    suitedFor: [
      "You like building things at the edge of what's settled",
      "You are comfortable when there is no single right answer",
      "You enjoy experimenting and measuring results",
      "You can be sceptical about impressive-looking output",
      "You want software skills plus something newer",
    ],
    challenges: [
      "The model is confidently wrong sometimes, and you must design for it",
      "Testing is hard when the same input can give different output",
      "Costs and latency add up quickly at real usage",
      "Best practices change faster than they can be written down",
      "It is easy to build a demo and hard to build something reliable",
    ],
    technologies: [
      "Python",
      "TypeScript",
      "LLM APIs",
      "Vector databases",
      "PostgreSQL",
      "Docker",
      "REST APIs",
    ],
    related: [
      "machine-learning-engineer",
      "backend-developer",
      "data-engineer",
      "full-stack-developer",
    ],
  },
  {
    slug: "machine-learning-engineer",
    name: "Machine Learning Engineer",
    shortDescription: "Train, evaluate and ship models that learn from data.",
    description:
      "A machine learning engineer builds systems that learn patterns from data instead of following rules someone wrote by hand. The job spans preparing data, training and evaluating models, and then the less glamorous half — getting a model into production where it runs reliably, stays monitored, and gets retrained as the world changes. It is mathematically heavier than most software roles.",
    mainFocus: "Models that learn from data",
    icon: "BrainCircuit",
    category: "DATA_AND_AI",
    difficulty: "ADVANCED",
    estimatedLearningTime: "12–18 months",
    demandLevel: "HIGH",
    builds: [
      "Recommendation and ranking systems",
      "Fraud and anomaly detection",
      "Forecasting and prediction models",
      "Computer vision and speech systems",
      "Training and deployment pipelines",
    ],
    learningAreas: [
      "Programming fundamentals",
      "Python",
      "Mathematics: linear algebra, statistics, calculus",
      "Data handling and cleaning",
      "Classical machine learning",
      "Deep learning",
      "Model evaluation",
      "Git and GitHub",
      "Deployment and monitoring of models",
    ],
    suitedFor: [
      "You enjoy mathematics and statistics",
      "You are patient with experiments that mostly fail",
      "You like rigorous measurement over intuition",
      "You are comfortable with uncertainty in results",
      "You want to work close to research",
    ],
    challenges: [
      "The mathematics is genuinely demanding",
      "Most of the work is data preparation, not modelling",
      "A model that scores well can still fail in production",
      "Training is slow and expensive to iterate on",
      "Entry-level roles often expect a strong quantitative background",
    ],
    technologies: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "NumPy",
      "Pandas",
      "Docker",
      "SQL",
    ],
    related: ["ai-engineer", "data-scientist", "data-engineer", "software-engineer"],
  },
  {
    slug: "data-scientist",
    name: "Data Scientist",
    shortDescription: "Answer real questions with statistics and experiments.",
    description:
      "A data scientist turns messy data into decisions someone can act on. That might mean designing an experiment to test whether a change actually helped, digging into why a number moved, or building a model to estimate something the business cares about. A large part of the job is communication: an analysis nobody understands or trusts changes nothing.",
    mainFocus: "Insight and experimentation",
    icon: "LineChart",
    category: "DATA_AND_AI",
    difficulty: "ADVANCED",
    estimatedLearningTime: "9–14 months",
    demandLevel: "HIGH",
    builds: [
      "Experiments and A/B tests",
      "Statistical models and forecasts",
      "Deep-dive analyses of product behaviour",
      "Metrics and definitions a company relies on",
      "Reports and visualisations for decision makers",
    ],
    learningAreas: [
      "Programming fundamentals",
      "Python",
      "Statistics and probability",
      "SQL",
      "Data cleaning and exploration",
      "Data visualisation",
      "Experiment design",
      "Machine learning basics",
      "Communicating results clearly",
    ],
    suitedFor: [
      "You are curious about why things happen",
      "You like statistics and careful reasoning",
      "You can explain a complex finding simply",
      "You are sceptical of results that look too good",
      "You want influence over decisions, not just code",
    ],
    challenges: [
      "Real data is messy, incomplete and often wrong",
      "Correlation constantly looks like causation",
      "Stakeholders may want the answer they already believe",
      "The role means very different things at different companies",
      "Strong statistics knowledge is expected, not optional",
    ],
    technologies: ["Python", "SQL", "Pandas", "NumPy", "Jupyter", "PostgreSQL"],
    related: [
      "data-analyst",
      "machine-learning-engineer",
      "data-engineer",
      "ai-engineer",
    ],
  },
  {
    slug: "data-analyst",
    name: "Data Analyst",
    shortDescription: "Turn raw numbers into clear answers people can use.",
    description:
      "A data analyst helps an organisation understand what is actually happening. You pull data out of databases, check whether it means what people think it means, and present it as dashboards and reports that answer specific questions. It is one of the most approachable ways into tech: the tools are learnable quickly, and the skill that matters most — asking the right question — doesn't require a computer science background.",
    mainFocus: "Reporting and business insight",
    icon: "BarChart3",
    category: "DATA_AND_AI",
    difficulty: "BEGINNER",
    estimatedLearningTime: "4–7 months",
    demandLevel: "HIGH",
    builds: [
      "Dashboards teams check every morning",
      "Reports that answer a specific business question",
      "Data quality and validation checks",
      "Metric definitions shared across a company",
      "Ad-hoc analyses for decisions in progress",
    ],
    learningAreas: [
      "Spreadsheets, properly",
      "SQL",
      "Data cleaning",
      "Statistics basics",
      "Data visualisation",
      "A BI tool such as Power BI or Tableau",
      "Python basics",
      "Communicating findings",
    ],
    suitedFor: [
      "You like finding the story inside a spreadsheet",
      "You enjoy answering practical questions",
      "You are organised and detail-oriented",
      "You want a route into tech without heavy programming first",
      "You like working with people across a business",
    ],
    challenges: [
      "Data is often inconsistent or undocumented",
      "Requests arrive vaguer than they sound",
      "Repetitive reporting can become tedious",
      "You may need to defend a finding people dislike",
      "Growth usually means learning programming eventually",
    ],
    technologies: ["SQL", "Python", "Excel", "Power BI", "Tableau", "PostgreSQL"],
    related: ["data-scientist", "data-engineer", "database-engineer"],
  },
  {
    slug: "data-engineer",
    name: "Data Engineer",
    shortDescription: "Build the pipelines that move and shape a company's data.",
    description:
      "A data engineer builds the plumbing everyone else depends on. Data arrives from many systems in inconsistent shapes; your job is to collect it, clean it, and land it somewhere reliable and queryable, on a schedule, without silently losing anything. Analysts and data scientists can only do their work if this layer is trustworthy, which makes it quietly one of the most important roles in a data team.",
    mainFocus: "Data pipelines and storage",
    icon: "Database",
    category: "DATA_AND_AI",
    difficulty: "ADVANCED",
    estimatedLearningTime: "9–13 months",
    demandLevel: "HIGH",
    builds: [
      "ETL and ELT pipelines",
      "Data warehouses and lakes",
      "Streaming ingestion systems",
      "Data quality and validation checks",
      "Scheduled jobs that run unattended",
    ],
    learningAreas: [
      "Programming fundamentals",
      "Python",
      "SQL, in depth",
      "Databases and data modelling",
      "Git and GitHub",
      "Batch and streaming processing",
      "Workflow orchestration",
      "Cloud data platforms",
      "Monitoring and reliability",
    ],
    suitedFor: [
      "You like building systems that run without you",
      "You care about correctness and reliability",
      "You enjoy SQL and thinking about data shapes",
      "You are comfortable with infrastructure",
      "You would rather enable others than present findings",
    ],
    challenges: [
      "Failures are often discovered downstream, late",
      "Upstream systems change without warning",
      "Debugging a pipeline at scale is slow",
      "Backfilling historical data is painful",
      "The work is invisible when it goes well",
    ],
    technologies: ["Python", "SQL", "PostgreSQL", "Apache Spark", "Airflow", "Docker"],
    related: [
      "backend-developer",
      "data-analyst",
      "database-engineer",
      "cloud-engineer",
    ],
  },
  {
    slug: "devops-engineer",
    name: "DevOps Engineer",
    shortDescription: "Automate the path from a commit to production traffic.",
    description:
      "A DevOps engineer makes shipping software safe and boring. You build the pipelines that test and release code, the infrastructure it runs on, and the monitoring that tells you when something breaks. The goal is that a developer can push a change and have it reach users quickly, repeatably, and with a way back if it goes wrong. It is as much about the process as the tooling.",
    mainFocus: "Delivery pipelines and infrastructure",
    icon: "Workflow",
    category: "INFRASTRUCTURE_AND_CLOUD",
    difficulty: "ADVANCED",
    estimatedLearningTime: "9–14 months",
    demandLevel: "HIGH",
    builds: [
      "CI/CD pipelines",
      "Infrastructure defined as code",
      "Container and orchestration setups",
      "Monitoring, logging and alerting",
      "Automated rollback and release strategies",
    ],
    learningAreas: [
      "Linux and the command line",
      "Networking basics",
      "Git and GitHub",
      "A scripting language such as Python or Bash",
      "Containers and Docker",
      "CI/CD tooling",
      "Infrastructure as code",
      "Cloud platforms",
      "Observability and incident response",
    ],
    suitedFor: [
      "You like automating anything you do twice",
      "You enjoy making other people's work easier",
      "You stay calm when something is broken",
      "You are interested in systems more than interfaces",
      "You like tools, pipelines and infrastructure",
    ],
    challenges: [
      "You are often on call when things fail",
      "The tooling landscape is wide and changes often",
      "Mistakes can affect every service at once",
      "It's rarely an entry-level role without prior experience",
      "Success is invisible; failure is very visible",
    ],
    technologies: [
      "Linux",
      "Docker",
      "Kubernetes",
      "Terraform",
      "AWS",
      "Git",
      "Python",
    ],
    related: [
      "cloud-engineer",
      "backend-developer",
      "solutions-architect",
      "cybersecurity-engineer",
    ],
  },
  {
    slug: "cloud-engineer",
    name: "Cloud Engineer",
    shortDescription: "Design infrastructure that scales without falling over.",
    description:
      "A cloud engineer designs and runs the infrastructure that applications live on, using platforms like AWS, Azure or Google Cloud. The work covers how services are laid out, how they talk to each other securely, how they scale under load, and what it all costs. Cost is a real part of the job — a design that works but is three times more expensive than it needs to be is not a good design.",
    mainFocus: "Cloud infrastructure and scale",
    icon: "Cloud",
    category: "INFRASTRUCTURE_AND_CLOUD",
    difficulty: "INTERMEDIATE",
    estimatedLearningTime: "7–11 months",
    demandLevel: "HIGH",
    builds: [
      "Cloud environments for whole products",
      "Networking, permissions and security boundaries",
      "Autoscaling and load-balanced services",
      "Backup and disaster recovery setups",
      "Cost optimisation across accounts",
    ],
    learningAreas: [
      "Linux and the command line",
      "Networking fundamentals",
      "One cloud platform, in depth",
      "Infrastructure as code",
      "Identity and access management",
      "Containers",
      "Monitoring and reliability",
      "Cost management",
    ],
    suitedFor: [
      "You like architecture and how pieces connect",
      "You enjoy working with infrastructure over interfaces",
      "You are careful about permissions and security",
      "You like measurable improvements such as cost or uptime",
      "You are comfortable reading long documentation",
    ],
    challenges: [
      "Each cloud provider is its own large ecosystem",
      "A misconfiguration can expose data publicly",
      "Costs can escalate quickly and quietly",
      "Certifications help but don't replace real experience",
      "Debugging distributed infrastructure is hard",
    ],
    technologies: ["AWS", "Terraform", "Linux", "Docker", "Kubernetes", "Python"],
    related: [
      "devops-engineer",
      "solutions-architect",
      "cybersecurity-engineer",
      "data-engineer",
    ],
  },
  {
    slug: "cybersecurity-engineer",
    name: "Cybersecurity Engineer",
    shortDescription: "Understand how systems break, then defend them.",
    description:
      "A cybersecurity engineer protects systems and data from people trying to misuse them. Depending on the role that might mean testing applications for weaknesses, designing defences, responding to incidents, or reviewing how a system is built before it ships. You need to understand how things work in detail before you can understand how they fail — which is why security is rarely a first job.",
    mainFocus: "Protecting systems and data",
    icon: "ShieldCheck",
    category: "SECURITY",
    difficulty: "ADVANCED",
    estimatedLearningTime: "10–16 months",
    demandLevel: "HIGH",
    builds: [
      "Security reviews and threat models",
      "Penetration tests and vulnerability reports",
      "Detection rules and monitoring",
      "Incident response processes",
      "Hardened infrastructure and access controls",
    ],
    learningAreas: [
      "Networking fundamentals",
      "Linux and operating systems",
      "Programming and scripting",
      "How web applications work",
      "Common vulnerability classes",
      "Cryptography basics",
      "Security tooling",
      "Incident response",
      "Compliance and risk basics",
    ],
    suitedFor: [
      "You are curious about how things can be broken",
      "You enjoy puzzles and dead ends",
      "You are ethical and careful with access",
      "You can document findings clearly",
      "You keep learning as attacks evolve",
    ],
    challenges: [
      "It requires broad knowledge before you can specialise",
      "Attackers only need one gap; you must cover all of them",
      "On-call and incident pressure is real",
      "Convincing teams to fix issues is a people problem",
      "Very few genuine entry-level positions exist",
    ],
    technologies: [
      "Linux",
      "Python",
      "Networking",
      "Wireshark",
      "Burp Suite",
      "Docker",
    ],
    related: [
      "devops-engineer",
      "cloud-engineer",
      "backend-developer",
      "qa-test-engineer",
    ],
  },
  {
    slug: "mobile-app-developer",
    name: "Mobile App Developer",
    shortDescription: "Build apps for the device in everyone's pocket.",
    description:
      "A mobile developer builds applications for phones and tablets. The constraints are different from the web: limited screen space, unreliable connectivity, battery life, and app stores that review what you ship. You either build natively for one platform, or use a cross-platform framework to target both from one codebase — each with real trade-offs.",
    mainFocus: "Native mobile experiences",
    icon: "Smartphone",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "BEGINNER",
    estimatedLearningTime: "6–10 months",
    demandLevel: "HIGH",
    builds: [
      "Consumer apps on the App Store and Play Store",
      "Offline-capable applications",
      "Apps using the camera, location or sensors",
      "Push notification systems",
      "Internal apps for field teams",
    ],
    learningAreas: [
      "Programming fundamentals",
      "A mobile language or framework",
      "Mobile UI patterns",
      "Git and GitHub",
      "Working with APIs",
      "Local storage and offline behaviour",
      "Device permissions",
      "Testing on real devices",
      "App store release process",
    ],
    suitedFor: [
      "You like building things people carry with them",
      "You care about polish and smooth interaction",
      "You enjoy working within tight constraints",
      "You want visible results quickly",
      "You are interested in device features like camera or GPS",
    ],
    challenges: [
      "Device and OS version fragmentation",
      "App store review can delay or block a release",
      "Debugging on real hardware is slower",
      "Native platforms mean learning two ecosystems",
      "Users update slowly, so old versions linger",
    ],
    technologies: ["Swift", "Kotlin", "React Native", "TypeScript", "Firebase", "Git"],
    related: [
      "frontend-developer",
      "full-stack-developer",
      "ui-ux-designer",
      "game-developer",
    ],
  },
  {
    slug: "game-developer",
    name: "Game Developer",
    shortDescription: "Build interactive worlds, systems and game feel.",
    description:
      "A game developer builds the systems that make a game work — movement, physics, rules, rendering, and the thousand small adjustments that make an action feel satisfying rather than merely functional. The technical bar is high, especially around performance and mathematics, and much of the craft is iteration: building something, playing it, and changing it until it feels right.",
    mainFocus: "Interactive systems and game feel",
    icon: "Gamepad2",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "ADVANCED",
    estimatedLearningTime: "10–16 months",
    demandLevel: "MODERATE",
    builds: [
      "2D and 3D games",
      "Game mechanics and physics systems",
      "Rendering and visual effects",
      "Tools that designers use to build levels",
      "Simulations and interactive experiences",
    ],
    learningAreas: [
      "Programming fundamentals",
      "A language such as C# or C++",
      "A game engine",
      "Mathematics: vectors, matrices, geometry",
      "Game loops and state",
      "Physics and collision",
      "Graphics basics",
      "Performance optimisation",
      "Git and GitHub",
    ],
    suitedFor: [
      "You want to build things that are played, not just used",
      "You enjoy mathematics and simulation",
      "You are patient with iteration and polish",
      "You like both creative and technical problems",
      "You are motivated by your own project ideas",
    ],
    challenges: [
      "Performance constraints are unforgiving",
      "The mathematics is heavier than most software roles",
      "The industry is competitive with demanding schedules",
      "Pay is often lower than equivalent roles elsewhere",
      "Finishing a game is much harder than starting one",
    ],
    technologies: ["C#", "C++", "Unity", "Godot", "Unreal Engine", "Git"],
    related: ["software-engineer", "mobile-app-developer", "embedded-systems-engineer"],
  },
  {
    slug: "blockchain-developer",
    name: "Blockchain Developer",
    shortDescription: "Write smart contracts and reason about trustless systems.",
    description:
      "A blockchain developer builds applications that run on decentralised networks, where code executes publicly and, once deployed, often cannot be changed. That permanence shapes everything: correctness matters enormously because a bug can be exploited by anyone and rarely patched. It is a specialised field with a smaller job market than mainstream software, and it moves in cycles.",
    mainFocus: "Decentralised applications and contracts",
    icon: "Boxes",
    category: "OTHER_TECHNOLOGY",
    difficulty: "ADVANCED",
    estimatedLearningTime: "9–14 months",
    demandLevel: "MODERATE",
    builds: [
      "Smart contracts",
      "Decentralised applications",
      "Token and payment systems",
      "Wallet integrations",
      "On-chain data tooling",
    ],
    learningAreas: [
      "Programming fundamentals",
      "JavaScript or TypeScript",
      "How blockchains actually work",
      "Solidity and the EVM",
      "Cryptography basics",
      "Smart contract security",
      "Testing and auditing",
      "Web frontends that talk to contracts",
      "Git and GitHub",
    ],
    suitedFor: [
      "You are interested in cryptography and distributed systems",
      "You are extremely careful about correctness",
      "You enjoy a young, fast-moving field",
      "You like open, publicly verifiable systems",
      "You are comfortable with volatility in the industry",
    ],
    challenges: [
      "Deployed bugs can be exploited immediately and irreversibly",
      "The job market rises and falls with the market",
      "Tooling is less mature than mainstream ecosystems",
      "Security expectations are unusually high for beginners",
      "Separating real engineering from hype takes judgement",
    ],
    technologies: ["Solidity", "TypeScript", "Ethereum", "Web3.js", "Node.js", "Git"],
    related: ["backend-developer", "software-engineer", "cybersecurity-engineer"],
  },
  {
    slug: "qa-test-engineer",
    name: "QA / Test Engineer",
    shortDescription: "Make sure software works before real users find out.",
    description:
      "A QA or test engineer is responsible for whether software actually does what it claims. That means designing test cases, automating the ones worth repeating, and thinking about the situations nobody planned for — the empty input, the double click, the expired session. Modern QA is heavily automated, so it is a genuine engineering role rather than manual clicking.",
    mainFocus: "Quality and correctness",
    icon: "Bug",
    category: "SOFTWARE_DEVELOPMENT",
    difficulty: "BEGINNER",
    estimatedLearningTime: "5–8 months",
    demandLevel: "MODERATE",
    builds: [
      "Automated test suites",
      "End-to-end browser tests",
      "Test plans for new features",
      "Bug reports developers can act on",
      "Testing steps inside CI pipelines",
    ],
    learningAreas: [
      "How software is built and released",
      "Programming fundamentals",
      "A test automation framework",
      "Git and GitHub",
      "API testing",
      "Test design and edge cases",
      "CI/CD basics",
      "Debugging and clear reporting",
    ],
    suitedFor: [
      "You notice when something is subtly wrong",
      "You think about what could go wrong before it does",
      "You are methodical and thorough",
      "You communicate problems clearly and without blame",
      "You want a route into engineering that starts gently",
    ],
    challenges: [
      "Finding problems can be mistaken for creating them",
      "Flaky tests erode trust in the whole suite",
      "QA is often under time pressure at the end of a cycle",
      "The role is undervalued at some companies",
      "Progressing usually means moving toward development",
    ],
    technologies: [
      "JavaScript",
      "TypeScript",
      "Playwright",
      "Cypress",
      "Python",
      "Git",
    ],
    related: [
      "software-engineer",
      "frontend-developer",
      "backend-developer",
      "cybersecurity-engineer",
    ],
  },
  {
    slug: "ui-ux-designer",
    name: "UI/UX Designer",
    shortDescription: "Decide how a product should work before it gets built.",
    description:
      "A UI/UX designer works out what a product should do and how it should feel to use, then expresses that as flows, wireframes and interface designs. UX is the thinking — research, structure, and whether a flow makes sense at all. UI is the craft — layout, type, colour and interaction. It is the least code-heavy path in this catalog, but the most collaborative.",
    mainFocus: "How the product works and feels",
    icon: "PenTool",
    category: "DESIGN_AND_PRODUCT",
    difficulty: "BEGINNER",
    estimatedLearningTime: "5–9 months",
    demandLevel: "MODERATE",
    builds: [
      "User flows and wireframes",
      "High-fidelity interface designs",
      "Design systems and component libraries",
      "Interactive prototypes",
      "Research findings and usability tests",
    ],
    learningAreas: [
      "Design fundamentals: layout, type, colour, hierarchy",
      "A design tool such as Figma",
      "User research methods",
      "Information architecture",
      "Prototyping",
      "Accessibility",
      "Design systems",
      "Basic HTML and CSS",
      "Communicating and defending decisions",
    ],
    suitedFor: [
      "You are interested in people as much as products",
      "You notice when something is confusing to use",
      "You enjoy visual craft and detail",
      "You can take critique without taking it personally",
      "You like collaborating across a team",
    ],
    challenges: [
      "Good work still gets rejected for business reasons",
      "You must justify decisions, not just present them",
      "Portfolios matter more than credentials, and take time",
      "Design and engineering constraints often conflict",
      "Junior roles are competitive",
    ],
    technologies: ["Figma", "HTML", "CSS", "Design systems", "Prototyping"],
    related: ["frontend-developer", "mobile-app-developer", "qa-test-engineer"],
  },
  {
    slug: "database-engineer",
    name: "Database Engineer",
    shortDescription: "Keep data correct, fast and available at scale.",
    description:
      "A database engineer specialises in the systems that store a company's data. The work covers schema design, query performance, replication and backups, and making sure the database keeps up as usage grows. When a product slows down, the answer is frequently in the database, and knowing how to find and fix it is a deep, durable skill.",
    mainFocus: "Data storage, integrity and performance",
    icon: "HardDrive",
    category: "INFRASTRUCTURE_AND_CLOUD",
    difficulty: "ADVANCED",
    estimatedLearningTime: "8–12 months",
    demandLevel: "MODERATE",
    builds: [
      "Schema designs that survive growth",
      "Query and index optimisation",
      "Replication and high-availability setups",
      "Backup and recovery procedures",
      "Migration plans for live systems",
    ],
    learningAreas: [
      "SQL, in depth",
      "Relational data modelling",
      "Indexing and query planning",
      "Transactions and consistency",
      "Backup and recovery",
      "Replication and scaling",
      "NoSQL trade-offs",
      "Linux basics",
      "Monitoring",
    ],
    suitedFor: [
      "You like precision and correctness",
      "You enjoy performance tuning and measurement",
      "You are calm about high-stakes changes",
      "You prefer depth in one area over broad variety",
      "You like being the person who finds the real bottleneck",
    ],
    challenges: [
      "Mistakes can mean data loss, so the stakes are high",
      "Migrations on live systems are stressful",
      "The role often expects prior backend experience",
      "Performance work needs real production data to be meaningful",
      "It is a narrower job market than general backend",
    ],
    technologies: ["PostgreSQL", "SQL", "MySQL", "Redis", "Linux", "Docker"],
    related: [
      "backend-developer",
      "data-engineer",
      "cloud-engineer",
      "solutions-architect",
    ],
  },
  {
    slug: "embedded-systems-engineer",
    name: "Embedded Systems Engineer",
    shortDescription: "Program the software inside physical devices.",
    description:
      "An embedded systems engineer writes software that runs on hardware rather than servers — inside appliances, cars, medical devices, sensors and industrial equipment. Memory and processing power are limited, updates may be difficult or impossible once shipped, and the software often has to interact directly with electronics. It sits at the boundary of software and hardware engineering.",
    mainFocus: "Software running on physical hardware",
    icon: "Cpu",
    category: "OTHER_TECHNOLOGY",
    difficulty: "ADVANCED",
    estimatedLearningTime: "10–16 months",
    demandLevel: "MODERATE",
    builds: [
      "Firmware for devices and appliances",
      "Sensor and IoT systems",
      "Real-time control software",
      "Device drivers",
      "Low-power connected products",
    ],
    learningAreas: [
      "Programming fundamentals",
      "C and C++",
      "How computers work at the hardware level",
      "Microcontrollers",
      "Electronics basics",
      "Real-time operating systems",
      "Communication protocols",
      "Debugging with hardware tools",
      "Memory and power constraints",
    ],
    suitedFor: [
      "You are interested in hardware as well as software",
      "You enjoy working within tight constraints",
      "You like low-level detail and precision",
      "You are patient with difficult debugging",
      "You want to build physical things",
    ],
    challenges: [
      "Debugging often needs physical equipment",
      "Memory and processing limits constrain every decision",
      "Shipped bugs may be impossible to patch",
      "The learning curve is steep and less beginner-friendly",
      "Fewer online resources than web development",
    ],
    technologies: ["C", "C++", "Rust", "Linux", "Microcontrollers", "Git"],
    related: ["software-engineer", "game-developer", "cybersecurity-engineer"],
  },
  {
    slug: "solutions-architect",
    name: "Solutions Architect",
    shortDescription: "Design how whole systems fit together, and why.",
    description:
      "A solutions architect decides the overall shape of a system — which components exist, how they communicate, where data lives, and which trade-offs are acceptable. The job is as much about constraints, cost and people as it is about technology, and it usually involves explaining a design to both engineers and non-technical stakeholders. It is a senior role that follows years of hands-on building.",
    mainFocus: "System design and trade-offs",
    icon: "Network",
    category: "INFRASTRUCTURE_AND_CLOUD",
    difficulty: "ADVANCED",
    estimatedLearningTime: "Builds on years of experience",
    demandLevel: "HIGH",
    builds: [
      "Architecture for large systems",
      "Integration designs between platforms",
      "Migration strategies for legacy systems",
      "Technical standards across teams",
      "Documented trade-off decisions",
    ],
    learningAreas: [
      "Strong software engineering foundations",
      "Databases and data modelling",
      "Networking and distributed systems",
      "Cloud platforms",
      "Security fundamentals",
      "Scalability and reliability patterns",
      "Cost awareness",
      "Documentation and communication",
    ],
    suitedFor: [
      "You enjoy the big picture as well as the detail",
      "You are good at explaining technical ideas to anyone",
      "You are comfortable making decisions under uncertainty",
      "You like weighing trade-offs rather than finding one answer",
      "You have or want years of hands-on experience first",
    ],
    challenges: [
      "It is not an entry-level role and cannot be shortcut",
      "You are accountable for decisions others implement",
      "You write and talk more than you code",
      "Requirements change after a design is agreed",
      "Being wrong is expensive and public",
    ],
    technologies: ["AWS", "Kubernetes", "PostgreSQL", "Docker", "Terraform", "Linux"],
    related: [
      "cloud-engineer",
      "devops-engineer",
      "backend-developer",
      "database-engineer",
    ],
  },
];
